// <auto-generated />
using System;
using DeveloperDetailsManagementSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeveloperDetailsManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521183918_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeveloperDetailsManagementSystem.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Nepal"
                        },
                        new
                        {
                            Id = 2,
                            Country = "India"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Bangladesh"
                        },
                        new
                        {
                            Id = 4,
                            Country = "China"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Pakistan"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Japan"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Uk"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Brazil"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Spain"
                        });
                });

            modelBuilder.Entity("DeveloperDetailsManagementSystem.Domain.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimateIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("DeveloperDetailsManagementSystem.Domain.Developer", b =>
                {
                    b.HasOne("DeveloperDetailsManagementSystem.Domain.Address", "Address")
                        .WithMany("Developers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DeveloperDetailsManagementSystem.Domain.Address", b =>
                {
                    b.Navigation("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
